###
# Configuration for Vagrant
###
name: ihh
language: fi
production:
  # This is used to automatically fetch data from a staging/production environment
  domain: ihhelsinki.fi-h.seravo.com
  ssh_port: 10220
  url: https://ihhelsinki.fi-h.seravo.com
development:
  # Domains are automatically mapped to Vagrant with /etc/hosts modifications or Avahi
  domains:
    - ihh.local
  # If you want to automatically pull stuff from production use 'always' or set
  # to 'never' to just silience the 'yes/no' question during 'vagrant up'.
  #pull_production_db: always
  #pull_production_plugins: always
  #pull_production_themes: always
